/* Simple Serial

A simple example of using serial data.

*/

#include <stdio.h>
#include "clixxIO.hpp"

class App : public clixxIOApp{

  public:
  
    void serialreceive(const char *datastring){
        /* serial data received Event handler
         
         This will get called when data is received.
         
        */

        printf("Serial data %s\n",datastring);
    };

    void startup(){
        /* startup Event handler

         This is a built in handler that will get called on startup
         and provides for initialisation requirements.
        */
        printf("Application in startup event\n");

        addSerialEvent("receive", (void (*)()) &App::serialreceive);
    };

};

// Main program Section. Simply setup an App class and let it run
main(){

  App m;

  m.run();

}

// Autogenerated interface between the event interface and application class
#include "serial-callbacks.cpp"
