/* Simple Timer

A simple example of using timers.

*/

#include <stdio.h>
#include "clixxIO.hpp"

class App : public clixxIOApp{

  public:
  
    void timerevent(){
        /* timer Event handler
         
         This will get called every second.
         
        */

        printf("Timer Callback\n");
    };
    
    void startup(){
        /* startup Event handler

         This is a built in handler that will get called on startup
         and provides for initialisation requirements.
        */
        printf("Application in startup event\n");

        addTimerEvent(2, (void (*)()) &App::timerevent);
    };
    
};

// Main program Section. Simply setup an App class and let it run
main(){
 
  App m;
  
  m.run();

}

// Autogenerated interface between the event interface and application class
#include "timer-callbacks.cpp"
