// ------------------------------------------------------------------------
// AUTO-GENERATED FILE - DO NOT EDIT
//
// This file is automatically generated. Any changes that you make
// here will be overridden.
// ------------------------------------------------------------------------
void C_timerevent( void* appC) { static_cast<App*>(appC)->timerevent(); }
void C_startupevent( void* appC) { static_cast<App*>(appC)->startup(); }
