/* Program

   A simple program created by the clixx.io generator now ready for 
   customisation.

*/

#include <stdio.h>
#include "clixxIO.hpp"
#include "serial-hbridge-config.hpp"

class App : public clixxIOApp{

  public:

    void setup(){
        /* setup Event handler

         This is a built in handler that will get called on startup
         and provides for initialisation requirements.

        */
        Serial.begin();
        Serial.puts("\r\nH-Bridge Motor Controller\r\n");
        Serial.puts("Commands are: 'f'=Forward,'r'=Reverse,'0'=Off\r\n");
        Serial.echo = 1;
        
        pin_rvs.configure(PB3,OUTPUT);
        pin_fwd.configure(PB4,OUTPUT);

    };

    void serialline(){
        
        /* SerialLine Event handler
         
         This gets called when a line is received.
         
        */
        char *cptr = (char *) Serial.lastline();
        char c = *cptr;
        
        if (c == 'f')
        {
            Serial.puts("Forward\r\n");
            pin_fwd.setval(1);
            pin_rvs.setval(0);
        }
        else if (c == 'r')
        {
            Serial.puts("Reverse\r\n");
            pin_fwd.setval(0);
            pin_rvs.setval(1);
        }
        else if (c == '0')
        {
            Serial.puts("Turned Off\r\n");
            pin_fwd.setval(0);
            pin_rvs.setval(0);
        } 
        else
        {
            Serial.puts("Command not understood. 'f'=Forward,'r'=Reverse,'0'=Off\r\n");
        }
        
    };

    clixxIOGPIOPin pin_rvs;
    clixxIOGPIOPin pin_fwd;
 
};

// Main program Section. Simply setup an App class and let it run
int main(){
 
  App m;
  
  return m.run();

}

// Autogenerated interface between the event interface and application class
#include "serial-hbridge-callbacks.cpp"
