// ------------------------------------------------------------------------
// AUTO-GENERATED FILE - DO NOT EDIT
//
// This file is automatically generated. Any changes that you make
// here will be overridden.
// ------------------------------------------------------------------------
void C_timerevent( void* appC) { }
void C_setupevent( void* appC) { static_cast<App*>(appC)->setup(); }
void C_loopevent ( void* appC) { static_cast<App*>(appC)->loop(); }
