/* Program

   A simple program created by the clixx.io generator now ready for 
   customisation.

*/

#include <stdio.h>
#include "clixxIO.hpp"
#include "remotebutton-config.hpp"

clixxIO_Button mybutton(BUTTON1_CONFIG);

class App : public clixxIOApp{

  private:
        
    int buttonstate;

  public:

    void setup(){
        /* setup Event handler
         * 
         * This is a built in handler that will get called on startup
         * and provides for initialisation requirements.
         * 
         */
        buttonstate = 0;

        Debug.begin();
        Debug.puts("Application in Startup event");

        IoT.beginPublishing("SmallDevice/Button");
    };

    void loop(){
        /* 
         * Loop Event handler - This gets called repeatedly.
         */
        if (mybutton.pressed()){

            Debug.puts("Button Pressed");

            buttonstate = ~buttonstate;
            if (buttonstate){
                IoT.publish("On");
            } 
            else {
                IoT.publish("Off");
            }
        }
    };

};

// Main program Section. Simply setup an App class and let it run
int main(){
 
  App m;

  return m.run();

}

// Autogenerated interface between the event interface and application class
#include "remotebutton-callbacks.cpp"
