// ------------------------------------------------------------------------
// AUTO-GENERATED FILE - DO NOT EDIT
//
// This file is automatically generated. Any changes that you make
// here will be overridden.
// ------------------------------------------------------------------------
void C_setupevent(     void* appC) { static_cast<App*>(appC)->setup(); }
void C_shutdownevent(  void* appC) {  }
void C_loopevent(      void* appC) {  }
void C_pinchange(      void* appC) {  }
void C_timerevent(     void* appC) {  } 

void C_serialchar(     void* appC) {  }
void C_serialline(     void* appC) { static_cast<App*>(appC)->serialline(); }
void C_serialopen(     void* appC) {  }
void C_serialclose(    void* appC) {  }

void C_iotmessage(     void* appC) {  }
void C_iotopen(        void* appC) {  }
void C_iotclose(       void* appC) {  }
