/* Program

   A simple program created by the clixx.io generator now ready for 
   customisation.

*/

#include <stdio.h>
#include "clixxIO.hpp"
#include "lightsensor-config.hpp"

class App : public clixxIOApp{

  public:

    void setup(){
        /* setup Event handler

         This is a built in handler that will get called on startup
         and provides for initialisation requirements.

        */
        Debug.puts("Application in Startup event");

    };

    void timer(){
        /* timer Event handler
         
         This will get called automatically by the timer.
         
        */
        Debug.puts("Timer Callback");
    };

};


// Main program Section. Simply setup an App class and let it run
int main(){
 
  App m;
  
  return m.run();

}

// Autogenerated interface between the event interface and application class
#include "lightsensor-callbacks.cpp"
