// ------------------------------------------------------------------------
// AUTO-GENERATED FILE
//
// This file is automatically generated. You may make changes to this file
// to add and remove callbacks.
// 
// ------------------------------------------------------------------------
void C_setupevent(     void* appC) { static_cast<App*>(appC)->setup(); }
void C_shutdownevent(  void* appC) {  }
void C_loopevent(      void* appC) { static_cast<App*>(appC)->loop(); }
void C_pinchange(      void* appC) {  }
void C_timerevent(     void* appC) {  } 

void C_serialchar(     void* appC) {  }
void C_serialline(     void* appC) { static_cast<App*>(appC)->serialline(); }
void C_serialopen(     void* appC) {  }
void C_serialclose(    void* appC) {  }

void C_iotmessage(     void* appC) { static_cast<App*>(appC)->iotmessage(); }
void C_iotopen(        void* appC) {  }
void C_iotclose(       void* appC) {  }
