/* Program

   A simple program created by the clixx.io generator now ready for 
   customisation.

*/

#include <stdio.h>
#include "clixxIO.hpp"
#include "iot-cricket85-config.hpp"

class App : public clixxIOApp{

  public:

    void setup(){
        /* setup Event handler

         This is a built in handler that will get called on startup
         and provides for initialisation requirements.

        */
        Debug.puts("Application in Startup event");

    };

    void loop(){
        /* Loop Event handler
         
         This gets called repeatedly.
         
        */
        Debug.puts("Loop Callback");
    };

    void serialline(){
        /* SerialLine Event handler
         
         This gets called when a line is received.
         
        */
        Debug.puts("SerialLine Callback");
    };

    void iotmessage(){
        /* IoT Message handler
         
         This gets called when an IoT sub is received.
         
        */
        Debug.puts("IoTMessage Callback");
    };

  private:
    const char inifile[] = "iot-cricket85.ini";
 
};


// Main program Section. Simply setup an App class and let it run
int main(){
 
  App m;
  
  return m.run();

}

// Autogenerated interface between the event interface and application class
#include "iot-cricket85-callbacks.cpp"
